"""
manager/helper/imgbb.py
══════════════════════════════════════════════════════════════════════════════
ImgBB thumbnail uploader.

Why ImgBB
─────────
In the distributed architecture, Workers run on different deployments and
cannot access each other's local filesystems.  Thumbnails must be stored
as publicly accessible HTTPS URLs so any Worker can download them.

Telegram file_ids are NOT shareable across bots — a file_id generated by
the Manager Bot is invalid for Worker Bots.  ImgBB solves this by giving
us a permanent, public HTTPS URL that any Worker can download with aiohttp.

Flow
────
  User sends a photo → Manager downloads it locally → upload_to_imgbb()
  → get back display_url → store in user.thumbnail_url (MongoDB)
  → all subsequent jobs carry thumbnail_url in the TASK message
  → Worker downloads thumbnail via aiohttp in pipeline._download_thumbnail()

Fallback
────────
If IMGBB_API_KEY is not set, thumbnail support is disabled and thumbnail_url
stays None.  Workers will attempt to use the original file's cover art.
══════════════════════════════════════════════════════════════════════════════
"""

from __future__ import annotations

import asyncio
import base64
import logging
import os
from typing import Optional

import aiohttp

from config import Config

logger = logging.getLogger(__name__)

_IMGBB_UPLOAD_URL = "https://api.imgbb.com/1/upload"
_TIMEOUT          = aiohttp.ClientTimeout(total=30)


async def upload_to_imgbb(image_path: str) -> Optional[str]:
    """
    Upload a local image file to ImgBB.

    Returns the display_url (direct HTTPS link to the image) on success,
    or None on failure.  Never raises.

    Parameters
    ──────────
    image_path : Absolute or relative path to the image file (JPEG/PNG/GIF/WEBP)
    """
    if not Config.IMGBB_API_KEY:
        logger.debug("[imgbb] IMGBB_API_KEY not set — skipping upload")
        return None

    if not os.path.isfile(image_path):
        logger.warning("[imgbb] File not found: %s", image_path)
        return None

    try:
        with open(image_path, "rb") as f:
            raw = f.read()
    except OSError as exc:
        logger.error("[imgbb] Cannot read %s: %s", image_path, exc)
        return None

    b64 = base64.b64encode(raw).decode()

    try:
        async with aiohttp.ClientSession(timeout=_TIMEOUT) as session:
            async with session.post(
                _IMGBB_UPLOAD_URL,
                data={"key": Config.IMGBB_API_KEY, "image": b64},
            ) as resp:
                if resp.status != 200:
                    body = await resp.text()
                    logger.error(
                        "[imgbb] Upload failed HTTP %d — %s",
                        resp.status, body[:200],
                    )
                    return None

                data = await resp.json()

        # Use the direct image URL (ends in .jpg/.png) — NOT display_url
        # which is an HTML viewer page (e.g. https://ibb.co/abc123).
        # data["data"]["image"]["url"] is always the raw CDN link.
        img_block = data.get("data", {}).get("image", {})
        url = img_block.get("url") or data.get("data", {}).get("url")
        if not url:
            logger.error("[imgbb] Response has no image.url: %s", data)
            return None

        logger.info("[imgbb] Uploaded thumbnail → %s", url)
        return url

    except asyncio.TimeoutError:
        logger.error("[imgbb] Upload timed out for %s", image_path)
        return None
    except Exception as exc:
        logger.error("[imgbb] Unexpected error: %s", exc)
        return None


async def delete_from_imgbb(delete_url: str) -> bool:
    """
    Attempt to delete an image from ImgBB using its delete_url.
    Returns True if the HTTP call succeeded (not necessarily that the image
    was actually deleted — ImgBB returns 200 even for already-deleted images).
    Never raises.
    """
    if not delete_url:
        return False
    try:
        async with aiohttp.ClientSession(timeout=_TIMEOUT) as session:
            async with session.get(delete_url) as resp:
                return resp.status == 200
    except Exception as exc:
        logger.debug("[imgbb] Delete failed: %s", exc)
        return False
